/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.snksport.UI;

import com.snksport.DAO.LoaiMatHangDAO;
import com.snksport.DAO.NhaCungCapDAO;
import com.snksport.Entity.LoaiMatHang;
import com.snksport.Entity.NhaCungCap;
import com.snksport.Utils.Auth;
import com.snksport.Utils.MsgBox;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThanhNam
 */
public class NhaCCvsLoaiMHJframe extends javax.swing.JInternalFrame {

    /**
     * Creates new form NhaCCJframe
     */
    public NhaCCvsLoaiMHJframe() {
        initComponents();
        fillTableNCC();
        fillTableLMH();
//        StatusNCC();
//        StatusLMH();
        clearFormLMH();
        clearFormNCC();
    }

    NhaCungCapDAO nccdao = new NhaCungCapDAO();
    LoaiMatHangDAO lmhdao = new LoaiMatHangDAO();
    int index = -1;

    void insertNCC() {
        NhaCungCap ncc = getFormNCC();

        try {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            } else {
                nccdao.insert(ncc);
                this.fillTableNCC();
                this.clearFormNCC();
                MsgBox.alert(this, "Thêm mới thành công!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }

    }

    void updateNCC() {
        NhaCungCap ncc = getFormNCC();
        try {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            } else {
                nccdao.update(ncc);
                this.fillTableNCC();
                MsgBox.alert(this, "Cập nhật thành công!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }

    }

    void deleteNCC() {
        int mancc = Integer.parseInt(lblMaNCC.getText());

        if (MsgBox.confirm(this, "Bạn có thực sự muốn xóa thông tin nhà cung cấp này?")) {
            try {
                if (!Auth.isManager()) {
                    MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
                } else {
                    nccdao.delete(mancc);
                    this.fillTableNCC();
                    this.clearFormNCC();
                    MsgBox.alert(this, "Xóa thành công!");
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thát bại!");
            }
        }
    }

    void editNCC() {
        int mancc = (int) tblNhaCungCap.getValueAt(this.index, 0);
        NhaCungCap ncc = nccdao.selectByID(mancc);
        this.setFormNCC(ncc);
        this.StatusNCC();
    }

    void fillTableNCC() {
        DefaultTableModel model = (DefaultTableModel) tblNhaCungCap.getModel();
        model.setRowCount(0);
        try {
            List<NhaCungCap> list = nccdao.selectAll(); //doc du lieu tu CSDL
            for (NhaCungCap ncc : list) {
                Object[] row = {
                    ncc.getMaNCC(),
                    ncc.getTenNCC(),
                    ncc.getDienThoai(),
                    ncc.getDiaChi()};
                model.addRow(row); //them 1 hang vao table
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void clearFormNCC() {
        NhaCungCap ncc = new NhaCungCap();
        setFormNCC(ncc);
        index = -1;
        StatusNCC();
    }

    void setFormNCC(NhaCungCap ncc) {
        lblMaNCC.setText(Integer.toString(ncc.getMaNCC()));
        txtNhaCC.setText(ncc.getTenNCC());
        txtSDT.setText(ncc.getDienThoai());
        txtDiaChi.setText(ncc.getDiaChi());
    }

    NhaCungCap getFormNCC() {
        NhaCungCap ncc = new NhaCungCap();
        ncc.setMaNCC(Integer.parseInt(lblMaNCC.getText()));
        ncc.setTenNCC(txtNhaCC.getText());
        ncc.setDienThoai(txtSDT.getText());
        ncc.setDiaChi(txtDiaChi.getText());
        return ncc;
    }

    void StatusNCC() {
        boolean edit = (this.index >= 0);

        //Trang thai form NCC
        btnThemNCC.setEnabled(!edit);
        btnSuaNCC.setEnabled(edit);
        btnXoaNCC.setEnabled(edit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhaCungCap = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNhaCC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnThemNCC = new javax.swing.JButton();
        btnSuaNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();
        btnMoiNCC = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblMaNCC = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiMatHang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnThemLMH = new javax.swing.JButton();
        btnSuaLMH = new javax.swing.JButton();
        btnXoaLMH = new javax.swing.JButton();
        btnMoiLMH = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtTenLMH = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMoTa = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblMaLMH = new javax.swing.JLabel();

        setTitle("SNKSport - Quản Lý Nhà Cung Cấp");
        setPreferredSize(new java.awt.Dimension(1080, 920));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "QUẢN LÝ NHÀ CUNG CẤP", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        tblNhaCungCap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NCC", "Tên Nhà Cung Cấp", "Số Điện Thoại", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhaCungCap);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tên NCC");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("SĐT");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Địa Chỉ");

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThemNCC.setBackground(new java.awt.Color(204, 255, 255));
        btnThemNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThemNCC.setText("Thêm");
        btnThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCCActionPerformed(evt);
            }
        });

        btnSuaNCC.setBackground(new java.awt.Color(204, 255, 255));
        btnSuaNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sua.png"))); // NOI18N
        btnSuaNCC.setText("Sửa");
        btnSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNCCActionPerformed(evt);
            }
        });

        btnXoaNCC.setBackground(new java.awt.Color(204, 255, 255));
        btnXoaNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoaNCC.setText("Xóa");
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });

        btnMoiNCC.setBackground(new java.awt.Color(204, 255, 255));
        btnMoiNCC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMoiNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new.png"))); // NOI18N
        btnMoiNCC.setText("Mới");
        btnMoiNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSuaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(btnMoiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMoiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Mã NCC: ");

        lblMaNCC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMaNCC.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaNCC)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtNhaCC, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txtSDT)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblMaNCC))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "QUẢN LÝ LOẠI MẶT HÀNG", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N

        tblLoaiMatHang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblLoaiMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã LMH", "Tên Loại Mặt Hàng", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiMatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiMatHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLoaiMatHang);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnThemLMH.setBackground(new java.awt.Color(204, 255, 255));
        btnThemLMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemLMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThemLMH.setText("Thêm");
        btnThemLMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLMHActionPerformed(evt);
            }
        });

        btnSuaLMH.setBackground(new java.awt.Color(204, 255, 255));
        btnSuaLMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaLMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sua.png"))); // NOI18N
        btnSuaLMH.setText("Sửa");
        btnSuaLMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLMHActionPerformed(evt);
            }
        });

        btnXoaLMH.setBackground(new java.awt.Color(204, 255, 255));
        btnXoaLMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaLMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        btnXoaLMH.setText("Xóa");
        btnXoaLMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLMHActionPerformed(evt);
            }
        });

        btnMoiLMH.setBackground(new java.awt.Color(204, 255, 255));
        btnMoiLMH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMoiLMH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/new.png"))); // NOI18N
        btnMoiLMH.setText("Mới");
        btnMoiLMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiLMHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSuaLMH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemLMH, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addComponent(btnMoiLMH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaLMH, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMoiLMH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemLMH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaLMH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaLMH, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tên LMH");

        txtTenLMH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtMoTa.setColumns(20);
        txtMoTa.setRows(5);
        jScrollPane3.setViewportView(txtMoTa);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Mô Tả");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Mã LMH:");

        lblMaLMH.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMaLMH.setText("...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTenLMH)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblMaLMH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lblMaLMH))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtTenLMH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCCActionPerformed
        // TODO add your handling code here:
        if (txtNhaCC.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống tên nhà cung cấp!");
            txtNhaCC.requestFocus();
            return;
        } else if (txtSDT.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống số điện thoại!");
            txtSDT.requestFocus();
            return;
        } else if (!txtSDT.getText().matches("((84)|(0))\\d{9}")) {
            MsgBox.alert(this, "Không đúng định dạng số điện thoại!");
            txtSDT.requestFocus();
            return;
        } else if (txtDiaChi.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống địa chỉ nhà cung cấp!");
            txtDiaChi.requestFocus();
            return;
        } else {
            insertNCC();
            MatHangJframe.it.fillComboBoxNhaCC();
        }


    }//GEN-LAST:event_btnThemNCCActionPerformed

    private void btnSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNCCActionPerformed
        // TODO add your handling code here:
        if (txtNhaCC.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống tên nhà cung cấp!");
            txtNhaCC.requestFocus();
            return;
        } else if (txtSDT.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống số điện thoại!");
            txtSDT.requestFocus();
            return;
        } else if (!txtSDT.getText().matches("((84)|(0))\\d{9}")) {
            MsgBox.alert(this, "Không đúng định dạng số điện thoại!");
            txtSDT.requestFocus();
            return;
        } else if (txtDiaChi.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống địa chỉ nhà cung cấp!");
            txtDiaChi.requestFocus();
            return;
        } else {
            updateNCC();
            MatHangJframe.it.fillComboBoxNhaCC();
        }
    }//GEN-LAST:event_btnSuaNCCActionPerformed

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        // TODO add your handling code here:
        deleteNCC();
        MatHangJframe.it.fillComboBoxNhaCC();
    }//GEN-LAST:event_btnXoaNCCActionPerformed

    private void btnMoiNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiNCCActionPerformed
        // TODO add your handling code here:
        clearFormNCC();
    }//GEN-LAST:event_btnMoiNCCActionPerformed

    private void tblNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhaCungCapMouseClicked
        // TODO add your handling code here:
        this.index = tblNhaCungCap.getSelectedRow();
        this.editNCC();
    }//GEN-LAST:event_tblNhaCungCapMouseClicked

    void insertLMH() {
        LoaiMatHang lmh = getFormLMH();

        try {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            } else {
                lmhdao.insert(lmh);
                this.fillTableLMH();
                this.clearFormLMH();
                MsgBox.alert(this, "Thêm mới thành công!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }

    }

    void updateLMH() {
        LoaiMatHang lmh = getFormLMH();
        try {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
            } else {
                lmhdao.update(lmh);
                this.fillTableLMH();
                MsgBox.alert(this, "Cập nhật thành công!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }

    }

    void deleteLMH() {
        int malmh = Integer.parseInt(lblMaLMH.getText());

        if (MsgBox.confirm(this, "Bạn có thực sự muốn xóa thông tin nhà cung cấp này?")) {
            try {
                if (!Auth.isManager()) {
                    MsgBox.alert(this, "Bạn không có quyền thực hiện chức năng này!");
                } else {
                    lmhdao.delete(malmh);
                    this.fillTableLMH();
                    this.clearFormLMH();
                    MsgBox.alert(this, "Xóa thành công!");
                }
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thát bại!");
            }
        }
    }

    void StatusLMH() {
        boolean edit = (this.index >= 0);

        //Trang thai form LMH
        btnThemLMH.setEnabled(!edit);
        btnSuaLMH.setEnabled(edit);
        btnXoaLMH.setEnabled(edit);
    }

    void editLMH() {
        int malmh = (int) tblLoaiMatHang.getValueAt(this.index, 0);
        LoaiMatHang lmh = lmhdao.selectByID(malmh);
        this.setFormLMH(lmh);
        StatusLMH();
    }

    void fillTableLMH() {
        DefaultTableModel model = (DefaultTableModel) tblLoaiMatHang.getModel();
        model.setRowCount(0);
        try {
            List<LoaiMatHang> list = lmhdao.selectAll(); //doc du lieu tu CSDL
            for (LoaiMatHang lmh : list) {
                Object[] row = {
                    lmh.getMaLMH(),
                    lmh.getTenLMH(),
                    lmh.getMoTa()};
                model.addRow(row); //them 1 hang vao table
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void clearFormLMH() {
        LoaiMatHang lmh = new LoaiMatHang();
        setFormLMH(lmh);
        index = -1;
        StatusLMH();
    }

    void setFormLMH(LoaiMatHang lmh) {
        lblMaLMH.setText(Integer.toString(lmh.getMaLMH()));
        txtTenLMH.setText(lmh.getTenLMH());
        txtMoTa.setText(lmh.getMoTa());
    }

    LoaiMatHang getFormLMH() {
        LoaiMatHang lmh = new LoaiMatHang();
        lmh.setMaLMH(Integer.parseInt(lblMaLMH.getText()));
        lmh.setTenLMH(txtTenLMH.getText());
        lmh.setMoTa(txtMoTa.getText());
        return lmh;
    }

    private void tblLoaiMatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiMatHangMouseClicked
        // TODO add your handling code here:
        this.index = tblLoaiMatHang.getSelectedRow();
        this.editLMH();
    }//GEN-LAST:event_tblLoaiMatHangMouseClicked

    private void btnThemLMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLMHActionPerformed
        // TODO add your handling code here:
        if (txtTenLMH.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống tên loại mặt hàng!");
            txtTenLMH.requestFocus();
//            return;
        } else {
            insertLMH();
            MatHangJframe.it.fillComboBoxLoaiMH();
        }
    }//GEN-LAST:event_btnThemLMHActionPerformed

    private void btnSuaLMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLMHActionPerformed
        // TODO add your handling code here:
        if (txtTenLMH.getText().length() == 0) {
            MsgBox.alert(this, "Không được để trống tên loại mặt hàng!");
            txtTenLMH.requestFocus();
//            return;
        } else {
            updateLMH();
            MatHangJframe.it.fillComboBoxLoaiMH();
        }
    }//GEN-LAST:event_btnSuaLMHActionPerformed

    private void btnXoaLMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLMHActionPerformed
        // TODO add your handling code here:
        deleteLMH();
        MatHangJframe.it.fillComboBoxLoaiMH();
    }//GEN-LAST:event_btnXoaLMHActionPerformed

    private void btnMoiLMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiLMHActionPerformed
        // TODO add your handling code here:
        clearFormLMH();
    }//GEN-LAST:event_btnMoiLMHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoiLMH;
    private javax.swing.JButton btnMoiNCC;
    private javax.swing.JButton btnSuaLMH;
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnThemLMH;
    private javax.swing.JButton btnThemNCC;
    private javax.swing.JButton btnXoaLMH;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMaLMH;
    private javax.swing.JLabel lblMaNCC;
    private javax.swing.JTable tblLoaiMatHang;
    private javax.swing.JTable tblNhaCungCap;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextArea txtMoTa;
    private javax.swing.JTextField txtNhaCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenLMH;
    // End of variables declaration//GEN-END:variables
}
